### ISSUE TITLE
Dynamic list of upcoming events

### ISSUE THREAD

**Issue by chtzvt** [TampaDevs/tampa.dev#1]
Since the new [Tampa Devs Events API](https://github.com/TampaDevs/events.api.tampa.dev) has launched, it'd be great to have an embeddable list of upcoming events on this site. 

Linked issue from the main site: https://github.com/TampaDevs/tampadevs/issues/8

**Comment by ebanner** [comment]
@chtzvt do you have a sense for how you'd like this to look? Like...

1. Just having a section of events at the bottom of the page
2. Plugging in the next event for each group in their group card
3. Making the site have multiple pages (like a groups page and an events page)
4. ??

**Comment by chtzvt** [comment]
Implemented.
