### ISSUE TITLE
Hoempage Carousel Widget Borked on Mobile

### ISSUE THREAD

**Issue by chtzvt** [TampaDevs/tampa.dev#3]
I spent some time today replacing the rss.app widgets with all-new widgets served by https://events.api.tampa.dev.

For the most part, the layout is OK. But there's currently a layout issue on iOS browsers specifically.

How it should look (using the Chrome simulator):

<img width="506" alt="Screenshot 2024-03-23 at 15 13 27" src="https://github.com/TampaDevs/tampa.dev/assets/7227500/381b2831-3c55-4ab7-92d0-d924743d31fc">

How it actually looks (on an actual iPhone):
![IMG_7813](https://github.com/TampaDevs/tampa.dev/assets/7227500/8f16de29-83f8-4b6d-8790-e5409e1c30e5)

**Comment by chtzvt** [comment]
Reopening this issue as the sizing is still b0rked on mobile iOS (even after #8):

![IMG_7815](https://github.com/TampaDevs/tampa.dev/assets/7227500/45ed7985-ab1e-476d-b37e-f4f8c299785b)

**Comment by manuelosorio** [comment]
@chtzvt I was looking at it might be a caching issue at this point. My change is not reflecting on the widget at all.

**Comment by ebanner** [comment]
Is this issue actually fixed? I can't find the carousel you're referring to.

I saw this section is cut off a little on mobile 

![image](https://github.com/TampaDevs/tampa.dev/assets/2068912/1c9b54c1-5b14-423f-8fc1-7f58a381e4be)

**Comment by chtzvt** [comment]
@ebanner The carousel is displayed on https://tampa.dev, and served from https://events.api.tampa.dev/widget/carousel. 

As for the cut off section-- that's an issue with the Open Collective contributors embed on https://tampadevs.com. We can track that issue in https://github.com/tampadevs/tampadevs :)

**Comment by ebanner** [comment]
Ah ok cool haha. Can confirm carousel looks good for me 👍 😁

**Comment by ebanner** [comment]
https://github.com/TampaDevs/tampadevs/issues/165
